### ISSUE TITLE
Make the game online

### ISSUE THREAD

**Issue by dimtion** [OtterLine/innovGame#5]
So the next big step :footprints:  is to make the game :video_game:  online :signal_strength:  so I suggest 2 frameworks:
 - [Flask](http://flask.pocoo.org/) :snake: With its framework for sockets : https://flask-socketio.readthedocs.io/en/latest/
 - [NodeJS](https://nodejs.org/en/)

What do you think ?

**Comment by nimag42** [comment]
I don't know either of these two, so I trust you.
Are there complementary or you want us to choose one ?

**Comment by nimag42** [comment]
The problem with Flask is that we need to set up a true deployment env, we can't use github-pages anymore :cry: ...
Maybe we should develop every thing we can in a first step with NodeJS then move to Flask for production need ?

**Comment by nimag42** [comment]
Should we consider refactoring the whole code using NodeJS then ? 

Maybe it will enhance perf.

**Comment by nimag42** [comment]
Okay, so after fair choosing (flip a coin), we decdided to split the project in two, sever-side and client-side.

## Server side
The server side will run with Flask, contacting the client with websockets using flask-websocket.io
Each type websockets will raise a callback methods, this callbacks should give the information in a in-memory no-sql database : [redis](http://redis.io).
Then a process will fetch every frame information in queue and process them, launching requests to client for informing them the new information

## Client side
The client will be recoded using Pixi.JS for improving performance.
The client will run websockets to tell player's actions : jump, flip.
The clients will listen to websockets to know other player's actions.

The client will just calculate position if nothing is given, then display it.

## Exchanges

Every messages is accompanied by a Unix timestamp.

Client :arrow_forward: Server:
- Jump_Up: Player_Number
- Jump_Down: Player_Number
- Flip: Player_Number

Client :arrow_backward: Server:
- Jump_Up : Player_Number
- Jump_Down : Player_Number
- Flip : Player_Number
- Pop_Food : position + TTL
- Eaten_Food : Food_Id + Player_Number
-  Win : Player_Number

**Comment by nimag42** [comment]
Updated projects and create two milestones
Let's close this brainstorming issue and focus on milestones.
